sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - "/^v?[0-9\\.]+/"
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=trunk
    - php: 7.0
      env: WP_VERSION=trunk
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest WP_PULUGIN_DEPLOY=1

env:
  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/customer-chat-for-facebook-messenger/
    - secure: "ELYqsJeyKC0iUePPn4OcaBvVYeLbgDvF3NK2Q4+RLKdol8U63YX9yxd7U3kJi4jl2WpUILIj8mPsVNGtoIEag+eqIKrvLQNlSrDFudeGFSUJcT5SWMSBarVAxnT9EJQxKyUCHT32toj3d5bu5ztQf/kfwPflBfvAhGTDcFXIdj+VpRHLSinLS2phri/swvYIQ2KIdXDbsXHVtYcVb9stgvS/N++OrS+wfP1Phwb0siYNzO1OSEIbYLp9j/Hmn7xyc1zBigNBLTfJ1eXwBniUVgXE30UgyvB99M5Qai+G9pQ5hN7yKVe79+1NYkYPcw5BKjXTQA3ZuxquqtFokHsOVy53dRy+k1xPzSH1oQT30Yw0GNlj0XpOxttAqWGs16QJUdwTDoA7jrgLITCW0PhGOMaUpO4OgxPTZTcyTgC4VfL78B9LADlTD1mJCzuhbpWCApgmYDAPwoHu2oFcsn5KHGjTZQRtSvwDbvhKUXir+55WowBXQ8SHU2DgfOTV/atN3ZyXRWzMlGaI62lpplv36p88X8aS1+vUtUCRrmCmMID192hsdC7YSCoSOKzX73uaM09Ro8RuACxHT92QG7AHIS1b78e+uyaDlaXVM6JTPXDJaDCMcSQIoW6RgzbBGkUKOK9S54Gt9yFRKVRzc+2WrUBmvjOVq2Ui2eIcSNzAMrQ="

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi

script:
  - phpunit

after_success: bash bin/deploy.sh
