sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=trunk
    - php: 7.0
      env: WP_VERSION=trunk
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest WP_PULUGIN_DEPLOY=1

env:
  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/customer-chat-for-facebook-messenger/
    - secure: "h4xcZ62JzH4smMhz/beZ0Qh0voH3smUer01Lnktqk3ZE9zuld3rt5sFe7zStSZfPNENsPpkwFeSETUh0ZtdG0EwSOBvflBXH+iSPZlh92gnC5GBCiYTrvm+eT34Lk0av5BAKY0sxvmqN2CuB1FX1dVvrEz7QK/r7vqRTfKQgEGqb4nP+l6XTnruTeCHUAySCBs9uNk4fWE51eATHo+9XudZNeR+x0Fz8Ae1Z5EnHmd50rPSPQbJ49wQ3/gwQByuV7XbSbH8Wo91nz0lpXnHPqt1QLfgSm7sZV996OeXuG+16JI5MS9uKwKdMVlh+8uc/3jSK9QrD9Is6wRFGUCqWN9xHSl0o9UxAWV0TCLilZ24pCNNLITwW5umrZUJuRy5cfPOIXbJEW8NqD2A4CkV/z5muC6/bHODe5A43OBtNTCVtVrJ4flaLRSo6FhUNqJOOEMCTvqocTN1TDlPYh+MhcZlt/y8W9ErHTvPJfm2UFdbwhs8MLbL8ZdOID4ErWU4/zKXrIgYq4x1iNALSifxyDJt/GlKAzcTgm1O1Z4LKahQhNdNDuzwvpvfrNShK0WeLmFJwn3Z/cg3JLRsBQ/ta8YAn6gyD68crvSL+NyoPfZloWWimiuPeE0hVLca2YkHWCPsPRhM4UwU8wWrV7B7FEHndG3ZrpD4E3ZLi9cbax2E="

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi

script:
  - phpunit

after_success: curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | bash
