sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - "/^v?[0-9\\.]+/"
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=trunk
    - php: 7.0
      env: WP_VERSION=trunk
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest WP_PULUGIN_DEPLOY=1

env:
  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/customer-chat-for-facebook-messenger/

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi

script:
  - phpunit

after_success: bash bin/deploy.sh
