sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - "/^v?[0-9\\.]+/"
cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=trunk
    - php: 7.0
      env: WP_VERSION=trunk
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest WP_PULUGIN_DEPLOY=1

env:
  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/customer-chat-for-facebook-messenger/
    - secure: "OzIxt0o8F9qEUFvBGO7BFqZs4/WEKomaB6yVsK1zb6Gw0CSt2vZBN+k6RdweZgCR1sTYXBPrwG4cVhu8pvpq8tGbsroIa9t7g6S75scYsL7dQsVASedEgmyj+l8A+5UrMGrx7HqEhGyG9/JXNSl5CK3sKO7GnKo0QzKFV/GeIVUIkyLDjrs/rZ/x0guGGSxds7Lclg2gRRjBg9ovFb3IapaVYBDHh5gTp2pCHPjho7A7uqA+vlP5wUeupbC3J7O5+YUCT+E8u5e+r5jDx7fu6h8WgHC4j8J1E4PsaoLBx/Wi4lgHgfdA1ixKm6AjCjlkou1maSbH4l6h6UP7nqrrWknsKSmMk1eX43IAR1palvd6rszbpBr+kXKitMiQ4/2hCgIc9dYTkCWGVjfpfXYDaodpZPjWSd1cZrvafr0cn6nzZuYPF2k8z5HLAD34QW8I67dLglSa+DxRGz0LpvfiafLTZL4dkiEKRagt0i6POMlO265wj1qjMjF5yFoORyhw4Jz8XEVXX7CkW1JCAX4m3i20UT0ifFw+OSKhO+8uOu6Udqoxwk2/GitkxTBFKjn7R6tUmNeqDNDw5mFzzUMMHwflWckQKZW/+ArXJjXZdxB+UZEU0OrNd7LRnx+HNMxUCE8iHF6kQkUJ6vVjanC+phl3Slq0q8zVjVtYbfpEBMc="

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi

script:
  - phpunit

after_success: curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | bash
